# Generated by Django 5.2.13 on 2026-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('panne', 'Panne'), ('anomalie', 'Anomalie'), ('securite', 'Sécurité'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('pris_en_charge', 'Pris en charge'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='signale', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'incident',
                'ordering': ['-created_at'],
            },
        ),
    ]
