# Generated by Django 5.2.13 on 2026-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_rename_historiquestatut_to_historiquestatutincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(choices=[('panne', 'Panne'), ('fuite', 'Fuite'), ('securite', 'Sécurité'), ('autre', 'Autre')], max_length=20),
        ),
    ]
