# Generated by Django 5.2.13 on 2026-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(max_length=100)),
                ('niveau_requis', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=20)),
                ('objets_lies', models.ManyToManyField(blank=True, related_name='services', to='objects.connectedobject')),
            ],
            options={
                'verbose_name': 'service',
            },
        ),
    ]
