# Generated by Django 5.2.13 on 2026-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_alerte_conso_kwh', models.FloatField(default=100.0, help_text='Seuil en kWh pour déclencher une alerte de consommation.')),
                ('seuil_alerte_co2_ppm', models.IntegerField(default=1000, help_text="Seuil en PPM pour déclencher une alerte de qualité de l'air (CO2).")),
                ('approbation_manuelle', models.BooleanField(default=True, help_text="Si coché, la suppression d'objet par un utilisateur standard requiert une approbation.")),
                ('domaines_email_autorises', models.JSONField(blank=True, default=list, help_text="Laisse vide pour autoriser tous les domaines. Sinon, liste de domaines autorisés pour l'inscription, ex: ['@civicsense.com']")),
            ],
            options={
                'verbose_name': 'paramètre global',
                'verbose_name_plural': 'paramètres globaux',
            },
        ),
    ]
