# Generated by Django 5.2.13 on 2026-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_collectedechet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedechet',
            name='heure',
            field=models.TimeField(default='07:00:00'),
        ),
    ]
