# Generated by Django 5.2.13 on 2026-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('type_objet', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'En maintenance')], default='actif', max_length=20)),
                ('connectivite', models.CharField(choices=[('wifi', 'Wi-Fi'), ('bluetooth', 'Bluetooth'), ('zigbee', 'Zigbee'), ('zwave', 'Z-Wave'), ('ethernet', 'Ethernet')], default='wifi', max_length=20)),
                ('signal_force', models.SmallIntegerField(default=0, help_text='dBm')),
                ('derniere_interaction', models.DateTimeField(blank=True, null=True)),
                ('consommation_kwh', models.FloatField(default=0.0)),
                ('batterie', models.SmallIntegerField(blank=True, help_text='%', null=True)),
                ('valeur_actuelle', models.JSONField(default=dict)),
                ('valeur_cible', models.JSONField(default=dict)),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('attributs_specifiques', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'objet connecté',
                'verbose_name_plural': 'objets connectés',
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'demande de suppression',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('valeur', models.FloatField()),
            ],
            options={
                'verbose_name': 'historique de consommation',
                'ordering': ['-date'],
            },
        ),
    ]
