# Generated by Django 5.2.13 on 2026-04-26 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrequest',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletionrequest',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='objects.connectedobject'),
        ),
        migrations.AddField(
            model_name='historiqueconso',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_conso', to='objects.connectedobject'),
        ),
        migrations.AlterUniqueTogether(
            name='historiqueconso',
            unique_together={('objet', 'date')},
        ),
    ]
