# Generated by Django 5.2.13 on 2026-04-30 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_connectedobject_type_objet_and_schema_rework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueconso',
            options={'ordering': ['-date'], 'verbose_name': 'historique de consommation', 'verbose_name_plural': 'historiques de consommation'},
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_alerte', models.CharField(choices=[('surconsommation_energie', 'Surconsommation énergie'), ('maintenance_requise', 'Maintenance requise'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('seuil', models.FloatField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('critique', 'Critique')], default='moyen', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_creees', to=settings.AUTH_USER_MODEL)),
                ('objet_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='objects.connectedobject')),
            ],
            options={
                'verbose_name': 'alerte',
                'verbose_name_plural': 'alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
