# Generated by Django 5.2.13 on 2026-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_historiqueconso_options_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='operateur',
            field=models.CharField(choices=[('gt', 'supérieur à (>)'), ('lt', 'inférieur à (<)'), ('gte', 'supérieur ou égal à (≥)'), ('lte', 'inférieur ou égal à (≤)')], default='gt', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='valeur_cle',
            field=models.CharField(blank=True, help_text='Clé JSON dans valeur_actuelle (type valeur_capteur)', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type_alerte',
            field=models.CharField(choices=[('surconsommation_energie', 'Surconsommation énergie'), ('batterie_faible', 'Batterie faible'), ('maintenance_requise', 'Maintenance requise'), ('valeur_capteur', 'Valeur capteur (JSON)'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
